

# This file was *autogenerated* from the file server_compute_template_P311_5var_faster.sage
from sage.all_cmdline import *   # import sage library

_sage_const_5 = Integer(5); _sage_const_3 = Integer(3); _sage_const_1 = Integer(1); _sage_const_46 = Integer(46); _sage_const_1024p0 = RealNumber('1024.0'); _sage_const_2 = Integer(2); _sage_const_4 = Integer(4); _sage_const_6 = Integer(6); _sage_const_10 = Integer(10); _sage_const_9 = Integer(9); _sage_const_0 = Integer(0); _sage_const_100 = Integer(100)
import time
import sys
import resource
from sage.all import *

NVARS = _sage_const_5 
TARGET_PARTITION = [_sage_const_3 , _sage_const_1 , _sage_const_1 ]
ESTIMATED_FINAL_DEGREE = _sage_const_46 

LOG_FILE = "progress_log_P311_5var_faster.txt"
OUTPUT_FILE = "FINAL_NUMERATOR_P311_5var.txt"

BR = QQ[",".join("x"+str(i) for i in range(_sage_const_1 , NVARS+_sage_const_1 ))+",z"]
x1, x2, x3, x4, x5, z = BR.gens()
BR.inject_variables()

Sym = SymmetricFunctions(QQ)
s = Sym.s()

def get_ram_mb():
    return resource.getrusage(resource.RUSAGE_SELF).ru_maxrss / _sage_const_1024p0 

def log_print(message):
    print(message)
    with open(LOG_FILE, "a") as f:
        f.write(message + "\n")

def do_P_k(k, n):
    global BR, NVARS
    CR = s[_sage_const_1 ].expand(NVARS).parent()
    return s[n].expand(NVARS).subs({CR.gens()[i] : BR('x'+str(i+_sage_const_1 ))**k for i in range(NVARS)})

@cached_function
def do_P_lambda(la, n):
    global BR, NVARS
    a = BR(expand(mul(do_P_k(p, n) for p in la) * mul(BR('x'+str(i+_sage_const_1 )) - BR('x'+str(j+_sage_const_1 )) for i in range(NVARS) for j in range(i+_sage_const_1 , NVARS))))
    return sum(c * mul(BR('x'+str(i+_sage_const_1 ))**(v[i] - (NVARS-i-_sage_const_1 )) for i in range(NVARS))                for (v,c) in a.dict().items() if all(v[i] > v[i+_sage_const_1 ] for i in range(NVARS-_sage_const_1 )))

@cached_function
def den_guess():
    global BR, x1, x2, x3, x4, x5, z
    m1 = (_sage_const_1  - x1**_sage_const_3 *x2**_sage_const_2 *z)
    m2 = (x1**_sage_const_4 *x2*z - _sage_const_1 )
    m3 = (x1**_sage_const_5 *z - _sage_const_1 )
    m4 = (x1**_sage_const_3 *x2*x3*z - _sage_const_1 )
    m5 = (x1**_sage_const_4 *x2**_sage_const_3 *x3**_sage_const_3 *z**_sage_const_2  - _sage_const_1 )
    m6 = (x1**_sage_const_4 *x2**_sage_const_4 *x3**_sage_const_2 *z**_sage_const_2  + x1**_sage_const_2 *x2**_sage_const_2 *x3*z + _sage_const_1 )
    m7 = (x1**_sage_const_6 *x2**_sage_const_2 *x3**_sage_const_2 *z**_sage_const_2  + x1**_sage_const_3 *x2*x3*z + _sage_const_1 )
    m8 = (x1**_sage_const_5 *x2**_sage_const_5 *z**_sage_const_2  - _sage_const_1 )
    m9 = (x1**_sage_const_5 *x2**_sage_const_5 *x3**_sage_const_5 *z**_sage_const_3  - _sage_const_1 )
    m10 = (x1**_sage_const_10 *x2**_sage_const_10 *z**_sage_const_4  + x1**_sage_const_5 *x2**_sage_const_5 *z**_sage_const_2  + _sage_const_1 )
    m11 = (x1**_sage_const_10 *x2**_sage_const_10 *x3**_sage_const_10 *z**_sage_const_6  + x1**_sage_const_5 *x2**_sage_const_5 *x3**_sage_const_5 *z**_sage_const_3  + _sage_const_1 )
    m12 = (_sage_const_1  - z**_sage_const_4 *x1**_sage_const_5 *x2**_sage_const_5 *x3**_sage_const_5 *x4**_sage_const_5 )
    m13 = (_sage_const_1  - z**_sage_const_2 *x1**_sage_const_4 *x2**_sage_const_4 *x3*x4)
    m14 = (_sage_const_1 - z**_sage_const_2 *x1**_sage_const_3 *x2**_sage_const_3 *x3**_sage_const_3 *x4)
    m15 = (_sage_const_1  - z**_sage_const_3  * x1**_sage_const_4  * x2**_sage_const_4  * x3**_sage_const_4  * x4**_sage_const_3 )
    m16 = (_sage_const_1  - z**_sage_const_6  * x1**_sage_const_9  * x2**_sage_const_9  * x3**_sage_const_6  * x4**_sage_const_6 )
    m17 = (_sage_const_1  - z**_sage_const_3 *x1**_sage_const_6 *x2**_sage_const_3 *x3**_sage_const_3 *x4**_sage_const_3 )
    m18 = (_sage_const_1  - z*x1*x2*x3*x4*x5)
    denominator_string = m1*m2*m3*m4*m5*m6*m7*m8*m9*m10*m11*m12*m13*m14*m15*m16*m17*m18
    return BR(denominator_string)

EXPANDED_DENOMINATOR = None

def get_den_expanded():
    global EXPANDED_DENOMINATOR
    if EXPANDED_DENOMINATOR is None:
        EXPANDED_DENOMINATOR = den_guess()
    return EXPANDED_DENOMINATOR

@cached_function
def den_coeff(d):
    global BR, z
    return get_den_expanded().coefficient({z: d})

def calc_num(la, d):
    return sum(den_coeff(d-r) * do_P_lambda(Partition(la), r) for r in range(d+_sage_const_1 ))

out = _sage_const_0 

with open(LOG_FILE, "a") as f:
    f.write(f"\n--- Starting Server Run for P_{TARGET_PARTITION} from scratch ---\n")

try:
    get_den_expanded()
except Exception as e:
    sys.exit(_sage_const_1 )

for d in range(_sage_const_0 , _sage_const_100 ): 
    start_time = time.time()
    
    CC = calc_num(TARGET_PARTITION, d)
    
    elapsed = time.time() - start_time
    current_ram = get_ram_mb()
    
    if CC:
        CC_list = list(CC)
        if len(CC_list) > _sage_const_6 :
            front = CC_list[:_sage_const_3 ]
            back = CC_list[-_sage_const_3 :]
            log_print(f"d={d:02d} | Terms: {len(CC_list):4d} | RAM: {current_ram:.0f} MB | Time: {elapsed:.2f}s\n  FRONT: {front}\n  BACK: {back}")
        else:
            log_print(f"d={d:02d} | Terms: {len(CC_list):4d} | RAM: {current_ram:.0f} MB | Time: {elapsed:.2f}s\n  {CC_list}")
        out += z**d * CC
        
        if (len(CC_list) <= _sage_const_1 ) and (d > _sage_const_0 ):
            with open(OUTPUT_FILE, "w") as f:
                f.write(f"Numerator_5var = {out}\n")
            break
    else:
        with open(OUTPUT_FILE, "w") as f:
            f.write(f"Numerator_5var = {out}\n")
        break

