

# This file was *autogenerated* from the file server_compute_template.sage
from sage.all_cmdline import *   # import sage library

_sage_const_5 = Integer(5); _sage_const_2 = Integer(2); _sage_const_1 = Integer(1); _sage_const_43 = Integer(43); _sage_const_1024p0 = RealNumber('1024.0'); _sage_const_4 = Integer(4); _sage_const_3 = Integer(3); _sage_const_0 = Integer(0); _sage_const_500 = Integer(500); _sage_const_8 = Integer(8); _sage_const_6 = Integer(6)
import time
import sys
import os
import resource
import numpy as np
from sage.all import *

# ==========================================
# CONFIGURATION
# ==========================================
NVARS = _sage_const_5  
TARGET_PARTITION = [_sage_const_2 ,_sage_const_1 ,_sage_const_1 ,_sage_const_1 ]
ESTIMATED_FINAL_DEGREE = _sage_const_43  # Set this to roughly 2x your bell-curve peak for the ETA

LOG_FILE = f"progress_log_P{''.join(map(str, TARGET_PARTITION))}_{NVARS}var.txt"
OUTPUT_FILE = f"FINAL_NUMERATOR_P{''.join(map(str, TARGET_PARTITION))}_{NVARS}var.txt"

BR = QQ[",".join("x"+str(i) for i in range(_sage_const_1 , NVARS+_sage_const_1 ))+",z"]
BR.inject_variables()
SymmetricFunctions(QQ).inject_shorthands(verbose=False)

def get_ram_mb():
    # Returns the max resident set size (RAM usage) in MB
    # Note: ru_maxrss is in kilobytes on Linux, bytes on macOS. 
    # Assuming standard Linux server environment:
    return resource.getrusage(resource.RUSAGE_SELF).ru_maxrss / _sage_const_1024p0 

def log_print(message):
    print(message)
    with open(LOG_FILE, "a") as f:
        f.write(message + "\n")

def do_P_k(k, n):
    global BR, NVARS
    CR = s[_sage_const_1 ].expand(NVARS).parent()
    return s[n].expand(NVARS).subs({CR.gens()[i] : BR('x'+str(i+_sage_const_1 ))**k for i in range(NVARS)})

@cached_function
def do_P_lambda(la, n):
    global BR, NVARS
    a = BR(expand(mul(do_P_k(p, n) for p in la) * mul(BR('x'+str(i+_sage_const_1 )) - BR('x'+str(j+_sage_const_1 )) for i in range(NVARS) for j in range(i+_sage_const_1 , NVARS))))
    return sum(c * mul(BR('x'+str(i+_sage_const_1 ))**(v[i] - (NVARS-i-_sage_const_1 )) for i in range(NVARS)) \
               for (v,c) in a.dict().items() if all(v[i] > v[i+_sage_const_1 ] for i in range(NVARS-_sage_const_1 )))

@cached_function
def den_guess():
    global BR
    # PASTE YOUR EXACT FACTORED DENOMINATOR HERE
    # Defaulted to P_{2,1} (3-Variable) for template completeness
    m1 = z*x1**_sage_const_5 
    m2 = z**_sage_const_2 *x1**_sage_const_5 *x2**_sage_const_5 
    m3 = z*x1**_sage_const_4 *x2 
    m4 = -z**_sage_const_2 *x1**_sage_const_5 *x2**_sage_const_5 
    m5 = z*x1**_sage_const_3 *x2**_sage_const_2 
    m6 = z*x1**_sage_const_3 *x2*x3
    m7 = -z*x1**_sage_const_3 *x2*x3
    m8 = z**_sage_const_2 *x1**_sage_const_4 *x2**_sage_const_4 *x3**_sage_const_2 
    m9 = z*x1**_sage_const_2 *x2**_sage_const_2 *x3
    m10 = -z**_sage_const_2 *x1**_sage_const_4 *x2**_sage_const_3 *x3**_sage_const_3 
    m11 = z**_sage_const_2 *x1**_sage_const_4 *x2**_sage_const_3 *x3**_sage_const_3 
    m12 = -z**_sage_const_3 *x1**_sage_const_5 *x2**_sage_const_5 *x3**_sage_const_5 
    m13 = z**_sage_const_3 *x1**_sage_const_5 *x2**_sage_const_5 *x3**_sage_const_5 
    m14 = -z**_sage_const_4 *x1**_sage_const_5 *x2**_sage_const_5 *x3**_sage_const_5 *x4**_sage_const_5 
    m15 = z**_sage_const_3 *x1**_sage_const_4 *x2**_sage_const_4 *x3**_sage_const_4 *x4**_sage_const_3 
    m16 = -z*x1**_sage_const_2 *x2*x3*x4
    m17 = z*x1**_sage_const_2 *x2*x3*x4
    m18 = z**_sage_const_2 *x1**_sage_const_3 *x2**_sage_const_3 *x3**_sage_const_2 *x4**_sage_const_2 
    m19 = -z**_sage_const_2 *x1**_sage_const_3 *x2**_sage_const_3 *x3**_sage_const_2 *x4**_sage_const_2 
    m20 = -z**_sage_const_2 *x1**_sage_const_4 *x2**_sage_const_4 *x3*x4
    m21 = z**_sage_const_2 *x1**_sage_const_4 *x2**_sage_const_4 *x3*x4
    m22 = -z**_sage_const_2 *x1**_sage_const_3 *x2**_sage_const_3 *x3**_sage_const_3 *x4
    m23 = -z*x1*x2*x3*x4*x5
    return BR((_sage_const_1 -m1)*(_sage_const_1 -m2)**_sage_const_2 *(_sage_const_1 -m3)*(_sage_const_1 -m4)*(_sage_const_1 -m5)*(_sage_const_1 -m6)**_sage_const_2 *(_sage_const_1 -m7)*(_sage_const_1 -m8)*(_sage_const_1 -m9)*(_sage_const_1 -m10)*(_sage_const_1 -m11)*(_sage_const_1 -m12)**_sage_const_2 *(_sage_const_1 -m13)*(_sage_const_1 -m14)*(_sage_const_1 -m15)*(_sage_const_1 -m16)**_sage_const_2 *(_sage_const_1 -m17)*(_sage_const_1 -m18)*(_sage_const_1 -m19)**_sage_const_2 *(_sage_const_1 -m20)*(_sage_const_1 -m21)*(_sage_const_1 -m22)*(_sage_const_1 -m23))

EXPANDED_DENOMINATOR = None

def get_den_expanded():
    global EXPANDED_DENOMINATOR
    if EXPANDED_DENOMINATOR is None:
        EXPANDED_DENOMINATOR = den_guess()
    return EXPANDED_DENOMINATOR

@cached_function
def den_coeff(d):
    global BR, z
    return get_den_expanded().coefficient({z: d})

def calc_num(la, d):
    return sum(den_coeff(d-r) * do_P_lambda(Partition(la), r) for r in range(d+_sage_const_1 ))

out = _sage_const_0 
time_history = []
degree_history = []

# Clear/create the log file
with open(LOG_FILE, "w") as f:
    f.write(f"--- Starting Server Run for P_{TARGET_PARTITION} ({NVARS} Variables) ---\n")

log_print("Warming up native denominator expansion... (takes a few seconds)")
get_den_expanded()
log_print("Expansion complete! Starting degrees...\n")

for d in range(_sage_const_0 , _sage_const_500 ): # Hard cap at 500 to prevent infinite runaways
    start_time = time.time()
    
    CC = calc_num(TARGET_PARTITION, d)
    
    elapsed = time.time() - start_time
    time_history.append(elapsed)
    degree_history.append(d)
    
    current_ram = get_ram_mb()
    
    eta_str = ""
    if d < ESTIMATED_FINAL_DEGREE and len(time_history) >= _sage_const_8 :
        try:
            # Mask out early warm-up degrees
            mask = np.array(degree_history) > _sage_const_6 
            x_data = np.array(degree_history)[mask]
            y_data = np.array(time_history)[mask]
            
            # Fit Log-Quadratic curve: log(time) = A*d^2 + B*d + C
            coeffs = np.polyfit(x_data, np.log(y_data), deg=_sage_const_2 )
            A, B, C = coeffs[_sage_const_0 ], coeffs[_sage_const_1 ], coeffs[_sage_const_2 ]
            
            remaining_degrees = np.arange(d + _sage_const_1 , ESTIMATED_FINAL_DEGREE + _sage_const_1 )
            predicted_times = np.exp(A * (remaining_degrees**_sage_const_2 ) + B * remaining_degrees + C)
            projected_remaining = np.sum(predicted_times)
            
            decay_factor = np.exp(_sage_const_2  * A)
            eta_str = f" | ETA to d={ESTIMATED_FINAL_DEGREE}: ~{projected_remaining/60:.1f} min (Decay: {decay_factor:.3f})"
        except Exception:
            eta_str = " | ETA: Calc..."
            
    if CC:
        CC_list = list(CC)
        if len(CC_list) > _sage_const_6 :
            front = CC_list[:_sage_const_3 ]
            back = CC_list[-_sage_const_3 :]
            log_print(f"d={d:02d} | Terms: {len(CC_list):4d} | RAM: {current_ram:.0f} MB | Time: {elapsed:.2f}s{eta_str}\n  FRONT: {front}\n  BACK: {back}")
        else:
            log_print(f"d={d:02d} | Terms: {len(CC_list):4d} | RAM: {current_ram:.0f} MB | Time: {elapsed:.2f}s{eta_str}\n  {CC_list}")
        out += z**d * CC
    else:
        # We hit exactly 0! The finite numerator has terminated.
        log_print(f"d={d:02d} | Terms:    0 | RAM: {current_ram:.0f} MB | Time: {elapsed:.2f}s")
        log_print(f"\n[SUCCESS] Numerator terminated at degree {d-1}!")
        
        # Write the final result to the output file
        with open(OUTPUT_FILE, "w") as f:
            f.write(f"# Exact Numerator for P_{TARGET_PARTITION} ({NVARS}-Variable)\n")
            f.write(f"# Terminated at degree {d-1}\n\n")
            f.write(f"Numerator_{NVARS}var = {out}\n")
            
        log_print(f"Saved complete numerator polynomial to {OUTPUT_FILE}.")
        break # Exit the loop immediately

